### ISSUE TITLE
你好，对你的工作Loosely-coupled Stereo-IMU-Wheel SLAM for Sweep Robot很感兴趣

### ISSUE THREAD

**Issue by tust13018211** [qiaozhijian/LPD-Net-Pytorch#1]
你好，如题，请问有任何论文、Code或者其他资料关于这个项目的吗，感觉比较有意思，感谢回复

**Comment by qiaozhijian** [comment]
您好，松耦合采用的是位姿图优化，就是不同传感器求出位姿，在时间上进行对齐后，进行位姿图优化。A Comparison of Graph Optimization Approaches for Pose Estimation in SLAM这篇论文对不同实现位姿图优化的库进行了比较。因为项目保密协议，代码不能开源。
